services:
  php:
    build: .
    container_name: php_tests
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:9000"
    environment:
      PHP_MEMORY_LIMIT: "512M"
      PHP_UPLOAD_MAX_FILESIZE: "50M"
      PHP_POST_MAX_SIZE: "50M"
      XDEBUG_MODE: "coverage"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge